// Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "user"
}

###
// Get All Users
GET http://localhost:5000/users

###
// Get Single User
GET http://localhost:5000/users/5c2eec30-b7ea-4a2f-a8be-83139ebb260b

###
// Update User
PATCH http://localhost:5000/users/eed11c4f-d762-4e8c-a9f9-ce371f39c647
Content-Type: application/json

{
    "name": "John Updated",
    "email": "john@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
// Delete User
DELETE http://localhost:5000/users/eed11c4f-d762-4e8c-a9f9-ce371f39c647

###
// Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "fitra@gmail.com",
    "password": "12345"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "12345"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout

###
// Get All Products
GET http://localhost:5000/products

###
//Get Single Product
GET http://localhost:5000/products/b91fb21e-1073-4a92-b686-62d04542750f

###
// POST Data product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Celana",
    "price": 80000
}

###
// Patch
PATCH http://localhost:5000/products/b91fb21e-1073-4a92-b686-62d04542750f
Content-Type: application/json

{
    "name": "Product Updated",
    "price": 80000
}

###
// Delete
DELETE http://localhost:5000/products/4e756eb5-c4a0-4ea2-90a9-f33f71bdc4d2